# Generated by Django 5.2.7 on 2026-01-27 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('edit_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('record_ID', models.UUIDField(default=uuid.uuid4)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'edit_history',
            },
        ),
    ]
