# Generated by Django 5.2.7 on 2026-01-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='value_type',
            field=models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('bool', 'Boolean'), ('text', 'Text')], default='float', max_length=10),
        ),
    ]
