# Generated by Django 5.2.7 on 2026-01-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='value_type',
            field=models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('bool', 'Boolean'), ('text', 'Text'), ('range', 'Range')], default='float', max_length=10),
        ),
    ]
