# Generated by Django 5.2.7 on 2026-01-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_metric_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='rule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
