# Generated by Django 5.2.7 on 2026-01-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_alter_metric_value_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='value_type',
            field=models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('bool', 'Boolean'), ('range', 'Range'), ('text', 'Text')], default='float', max_length=10),
        ),
    ]
