# Generated by Django 5.2.7 on 2026-02-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_alter_metric_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='possible_inputs',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
