# Generated by Django 5.2.7 on 2026-01-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_metric_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='option_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='option_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
