# Generated by Django 5.2.7 on 2026-01-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_metric_option_category_metric_option_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='option_class',
        ),
    ]
