# Generated by Django 5.2.7 on 2026-02-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_metric_possible_inputs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='possible_inputs',
        ),
        migrations.AddField(
            model_name='metric',
            name='scoring_dict',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
