# Generated by Django 5.2.7 on 2026-03-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_remove_metric_possible_inputs_metric_scoring_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
