# Generated by Django 5.2.7 on 2026-03-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0006_alter_metric_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="metric_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="metric",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("github_api", "GitHub API"),
                    ("scc", "SCC"),
                    ("gitstats", "GitStats"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
