# Generated by Django 5.2.7 on 2026-05-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0008_alter_metric_value_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_order",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object mapping category names to ordered lists of metric IDs",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Metric Orders",
            },
        ),
    ]
