# Generated by Django 5.2.7 on 2026-01-27 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('backup_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('backup_date', models.DateTimeField(auto_now_add=True)),
                ('backup_file', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('performedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_log',
            },
        ),
    ]
