# Generated by Django 5.2.7 on 2026-01-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='analysis_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='analysis_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='library',
            name='analysis_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
