# Generated by Django 5.2.7 on 2026-01-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_library_gitstats_error_library_gitstats_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='gitstats_report_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
