# Generated by Django 5.2.7 on 2026-01-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
        ('libraries', '0002_library_analysis_error_library_analysis_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='library_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='library',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('domain', 'library_name'), name='uniq_library_name_per_domain'),
        ),
    ]
