# Generated by Django 5.2.7 on 2026-01-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_remove_domain_created_by'),
        ('libraries', '0003_alter_library_library_name_alter_library_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('domain', 'url'), name='uniq_url_per_domain'),
        ),
    ]
