# Generated by Django 5.2.7 on 2026-03-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libraries", "0003_library_gitstats_report_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="programming_language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
