# Generated by Django 5.2.7 on 2026-03-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0005_domain_ahp_matrix_alter_domain_category_weights"),
        ("libraries", "0004_alter_library_programming_language"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="library",
            name="uniq_url_per_domain",
        ),
        migrations.RenameField(
            model_name="library",
            old_name="url",
            new_name="github_url",
        ),
        migrations.AddConstraint(
            model_name="library",
            constraint=models.UniqueConstraint(
                fields=("domain", "github_url"),
                name="uniq_github_url_per_domain",
            ),
        ),
    ]
