# Generated by Django 5.2.7 on 2026-03-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_domain_ahp_matrix_alter_domain_category_weights'),
        ('libraries', '0005_remove_library_uniq_url_per_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('domain', 'url'), name='uniq_url_per_domain'),
        ),
    ]
