# Generated by Django 5.2.7 on 2026-03-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0006_library_url_alter_library_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
