# Generated by Django 5.2.7 on 2025-11-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='Programming_Language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
