# Generated by Django 5.2.7 on 2025-11-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_library_programming_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymetricvalue',
            name='Value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
