# Generated by Django 5.2.7 on 2026-01-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_librarymetricvalue_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='Domain',
        ),
        migrations.RemoveField(
            model_name='librarymetricvalue',
            name='Library',
        ),
        migrations.RemoveField(
            model_name='librarymetricvalue',
            name='Collected_By',
        ),
        migrations.RemoveField(
            model_name='librarymetricvalue',
            name='Metric',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='LibraryMetricValue',
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
    ]
