# Generated by Django 5.2.7 on 2026-01-26 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="created_by",
        ),
        migrations.AddField(
            model_name="domain",
            name="creators",
            field=models.ManyToManyField(
                blank=True, related_name="created_domains", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
