# Generated by Django 5.2.7 on 2026-01-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_domain_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
