# Generated by Django 5.2.7 on 2026-01-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0002_remove_domain_created_by_domain_creators"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="paper_name",
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="paper_url",
            field=models.URLField(max_length=500, blank=True),
        ),
    ]

