# Generated by Django 5.2.7 on 2026-01-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_domain_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='created_by',
        ),
    ]
