# Generated by Django 5.2.7 on 2026-01-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_domain_created_by_domain_published'),
        ('domain', '0003_domain_paper_name_domain_paper_url'),
    ]

    operations = [
    ]
