# Generated by Django 5.2.7 on 2026-02-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_alter_domain_paper_name_alter_domain_paper_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='ahp_matrix',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='category_weights',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
