# Generated by Django 5.2.7 on 2026-01-27 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_merge_20260127_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='created_by',
        ),
    ]
