# Generated by Django 5.2.7 on 2026-03-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_metric_values', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarymetricvalue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
