# Generated by Django 5.2.7 on 2026-01-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_metric_values', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymetricvalue',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
