name: Manually Build PDF
on:
  workflow_dispatch:
    inputs:
        pdf_path:
            description: "The path to the pdf, not including the docs/ and file extension. For Example to update SRS: SRS-Volere/SRS" 
            required: true
            type: string
env:
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  update-pdfs:
    runs-on: ubuntu-latest
    if: ${{ inputs.pdf_path }} 
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Commit message
      id: commit-message
      env:
        file: ${{ inputs.pdf_path }}
      run: |
        COMMIT_MESSAGE="Add/Update pdf $file"
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
    - uses: xu-cheng/texlive-action@v2
      name: Compile LaTeX Files
      env:
        file: ${{ inputs.pdf_path }}
      with:
        scheme: full
        texlive_version: 2024
        run: |
          apk add make
          cd /github/workspace/docs
          file="${{ env.file }}"
          dir=$(dirname "$file" | cut -d'/' -f2-)
          make -B "$dir/$(basename "$file" .tex).pdf"
    - name: Commit and push PDFs
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ steps.commit-message.outputs.COMMIT_MESSAGE }}
        file_pattern: 'docs/**/*.pdf'
        branch: ${{ github.head_ref || github.ref_name }}
